global:
  name: CNCF Cloud Native Interactive Landscape
  short_name: CNCF
  mode: CNCF
  repo: cncf/landscape
  website: https://landscape.cncf.io
  short_domain: l.cncf.io
  company_url: https://www.cncf.io
  email: info@cncf.io
  self: https://www.crunchbase.com/organization/cloud-native-computing-foundation
  slack_channel: T08PSQ7BQ/BC07DVB0C/jqc0ANnvpVddAp651jgyMKdr
  meta:
    title: Cloud Native Landscape
    fb_admin: alex.contini.94
    description: >-
      The Cloud Native Landscape organizes all cloud native open source projects and proprietary products into categories, providing an overview of the current
      ecosystem
    twitter: '@CloudNativeFdn'
    google_site_verification: 8l35EQriJXntsib5sBdRu4gmDV1nAP9PSoHccJC8ABQ
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
    extra: >
      <meta property="og:image" content="https://landscape.cncf.io/images/social.jpg" />

      <meta property="og:image:width" content="1800" />

      <meta property="og:image:height" content="945" />

      <meta property="og:locale" content="en_US" />

      <meta property="og:type" content="website" />

      <meta property="og:title" content="Cloud Native Landscape" />

      <meta property="og:description" content="The Cloud Native Landscape organizes all cloud native open source projects and proprietary products into
      categories, providing an overview of the current ecosystem" />

      <meta property="og:url" content="https://landscape.cncf.io/" />

      <meta property="og:site_name" content="Cloud Native Landscape" />

      <meta name="twitter:card" content="summary_large_image" />

      <meta name="twitter:title" content="Cloud Native Landscape" />

      <meta name="twitter:description" content="The Cloud Native Landscape organizes all cloud native open source projects and proprietary products into
      categories, providing an overview of the current ecosystem" />

      <meta name="twitter:image" content="https://landscape.cncf.io/images/social.jpg" />

      <meta name="twitter:image:width" content="1800" />

      <meta name="twitter:image:height" content="945" />

      <script src="https://cmp.osano.com/16A0DbT9yDNIaQkvZ/c3494b1e-ff3a-436f-978d-842e9a0bed27/osano.js"></script>

      <link href="/images/cookie-banner.css" rel="stylesheet" type='text/css' media='all' />
  flags:
    hide_license_for_categories:
      - Special
      - CNCF Members
    hide_category_from_subcategories:
      - End User Supporter
twitter:
  search: landscape.cncf.io
  url: https://landscape.cncf.io
  text: Cloud Native Landscape from @CloudNativefdn
relation:
  label: CNCF Relation
  url: cncf
  values:
    - id: hosted
      label: CNCF Projects
      children:
        - id: graduated
          label: CNCF Graduated Projects
          prefix: CNCF
          tag: Graduated Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: CNCF Graduated
          big_picture_color: rgb(24,54,114)
        - id: incubating
          label: CNCF Incubating Projects
          prefix: CNCF
          tag: Incubating Project
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: CNCF Incubating
          big_picture_color: rgb(83, 113, 189)
        - id: sandbox
          label: CNCF Sandbox Projects
          prefix: CNCF
          tag: Sandbox Project
          color: '#d1f7ff'
          big_picture_label: CNCF Sandbox
          big_picture_color: rgb(108, 165, 209)
          additional_relation: member
        - id: archived
          label: Archived CNCF Projects
          prefix: CNCF
          tag: Archived Project
          color: '#d3d3d3'
          big_picture_label: CNCF Archived
          big_picture_color: rgb(211, 211, 211)
          additional_relation: member
    - id: member
      label: CNCF Member Products/Projects
      tag: CNCF Member
    - id: false
      label: Non-CNCF Member Products/Projects
      url: 'no'
membership: {}
home:
  header: >
    <h1>CNCF Cloud Native Interactive Landscape</h1> The cloud native landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>), serverless landscape (<a target="_blank" href="images/serverless.png">png</a>, <a target="_blank"
    href="images/serverless.pdf">pdf</a>), and member landscape (<a target="_blank" href="images/members.png">png</a>, <a target="_blank"
    href="images/members.pdf">pdf</a>) are dynamically generated below.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads: []
presets: []
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    short_name: Land...
    title: CNCF Cloud Native Landscape
    fullscreen_header: Overwhelmed? Please see the CNCF Trail Map. That and the interactive landscape are at l.cncf.io
    elements:
      - type: HorizontalCategory
        category: App Definition and Development
        rows: 8
        width: 1265
        height: 340
        top: 0
        left: 0
        color: rgb(109,61,143)
        is_large: false
      - type: HorizontalCategory
        category: Orchestration & Management
        rows: 4
        width: 1265
        height: 200
        top: 350
        left: 0
        color: rgb(46,107,46)
        is_large: false
      - type: HorizontalCategory
        category: Runtime
        rows: 5
        width: 1265
        height: 250
        top: 560
        left: 0
        color: rgb(143,88,61)
        is_large: false
      - type: HorizontalCategory
        category: Provisioning
        rows: 8
        width: 1265
        height: 310
        top: 825
        left: 0
        color: rgb(46,97,107)
        is_large: false
      - type: VerticalCategory
        category: Platform
        cols: 9
        width: 455
        height: 620
        top: 0
        left: 1285
        color: rgb(107,97,46)
        is_large: false
      - type: VerticalCategory
        category: Observability and Analysis
        cols: 10
        width: 455
        height: 900
        top: 660
        left: 1285
        color: rgb(107,61,46)
        is_large: false
      - type: HorizontalCategory
        category: Special
        rows: 10
        width: 1265
        height: 400
        top: 1160
        left: 0
        color: rgb(179,77,77)
        is_large: false
      - type: LandscapeInfo
        width: 370
        height: 280
        top: 1280
        left: 1760
        children:
          - type: text
            text: >
              This landscape is intended as a map through the previously uncharted terrain of cloud native technologies. There are many routes to deploying a
              cloud native application, with CNCF Projects representing a particularly well-traveled path.
            top: 80
            left: 120
            right: 20
            font_size: 12
          - type: image
            image: qr-l.svg
            top: 80
            left: 15
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.cncf.io
            top: 168
            left: 18
            font_size: 23
          - type: image
            image: right-logo.svg
            width: 109
            right: 15
            top: 15
            title: CNCF Logo
          - type: image
            image: left-logo.svg
            width: 140
            left: 15
            top: 15
            title: Landscape Logo
          - type: image
            image: amplify.svg
            width: 50
            right: 15
            top: 40
            title: Amplify Logo
          - type: image
            image: redpoint.svg
            width: 50
            right: 75
            top: 42
            title: Redpoint Logo
      - type: LandscapeLink
        url: serverless
        title: Serverless
        layout: category
        left: 1760
        top: 0
        width: 370
        height: 270
        color: rgb(64,117,191)
      - type: LandscapeLink
        url: members
        title: Members
        layout: category
        left: 1760
        top: 305
        width: 370
        height: 270
        color: rgb(64,117,191)
      - type: LandscapeLink
        url: https://landscape.cd.foundation
        image: https://landscape.cd.foundation/images/landscape_preview.png
        title: CD Foundation Landscape
        layout: category
        left: 1760
        top: 610
        width: 370
        height: 270
        color: rgb(64,117,191)
  extra:
    tab_index: 2
    url: serverless
    name: Serverless
    short_name: Server...
    title: CNCF Serverless Landscape
    fullscreen_header: See the serverless interactive display at s.cncf.io
    elements:
      - type: HorizontalCategory
        category: Tools
        rows: 1
        width: 570
        height: 90
        top: 0
        left: 0
        color: rgb(143,109,61)
        fit_width: true
        is_large: false
      - type: HorizontalCategory
        category: Framework
        rows: 1
        width: 820
        height: 90
        top: 100
        left: 0
        fit_width: true
        offset: 10
        color: rgb(102,61,143)
        is_large: false
      - type: HorizontalCategory
        category: Security
        rows: 1
        width: 240
        height: 90
        top: 0
        left: 580
        color: rgb(179,94,77)
        fit_width: true
        offset: 40
        is_large: false
      - type: HorizontalCategory
        category: Hosted Platform
        rows: 2
        width: 480
        height: 120
        top: 200
        left: 0
        fit_width: true
        color: rgb(83,115,38)
        is_large: false
      - type: HorizontalCategory
        category: Installable Platform
        rows: 2
        width: 330
        height: 120
        top: 200
        left: 490
        fit_width: true
        color: rgb(83,115,38)
        is_large: false
      - type: LandscapeInfo
        width: 520
        height: 120
        top: 330
        left: 0
        children:
          - type: text
            text: >
              Serverless computing refers to a new model of cloud native computing, enabled by architectures that do not require server management to build and
              run applications. This landscape illustrates a finer-grained deployment model where applications, bundled as one or more functions, are uploaded
              to a platform and then executed, scaled, and billed in response to the exact demand needed at the moment
            font_size: 9
            top: 10
            left: 90
            right: 150
          - type: image
            title: QR Code
            width: 70
            height: 70
            top: 10
            left: 5
            image: qr-s.svg
          - type: title
            title: s.cncf.io
            font_size: 16
            top: 75
            left: 10
          - type: image
            title: Landscape Logo
            width: 110
            top: 10
            right: 15
            image: left-logo.svg
          - type: image
            title: CNCF Logo
            width: 109
            top: 45
            right: 15
            image: right-logo.svg
          - type: image
            title: Redpoint Logo
            width: 109
            top: 70
            right: 15
            image: redpoint.svg
      - type: LandscapeLink
        url: landscape
        title: Cloud Native Landscape
        layout: subcategory
        left: 635
        top: 325
        width: 185
        height: 125
        color: rgb(64,117,191)
    category: Serverless
test:
  header: CNCF Cloud Native Interactive Landscape
  section: CNCF Graduated Projects
  logo: kubernetes.svg
anonymous_organization:
  name: Non-Public Unnamed Organization
  homepage: https://www.cncf.io
  city: Bouvet Island
  region: Antarctica
  country: Antarctica
  twitter: https://twitter.com/CloudNativeFdn
prerender: {}
export: {}
